### ISSUE TITLE
Disappearing topics

### ISSUE THREAD

**Issue by AlexG2222** [yariplus/nodebb-plugin-category-sort-by-title#2]
There is an issue with disappearing topics with the plugin category-sort-by-tile. When sort by A-Z or Z-A is activated there are some topics that are not displayed anymore. They reappear if sort by is changed to one of the standard options. 

It's always the same topics that are disappearing and reappearing. But I couldn't really figure out anything special about these topics or what they have in common.

**Comment by yariplus** [comment]
Hey there! Let me know if new topics are still disappearing after clicking re-index in the admin page. Thanks!
