### ISSUE TITLE
Not working anymore on NodeBB v.13.x

### ISSUE THREAD

**Issue by AlexG2222** [yariplus/nodebb-plugin-category-sort-by-title#3]
Hi there!

The plugin is not working anymore since I upgraded to the latest NodeBB version. It just doesn't show any topics anymore and re-indexing doesn't help. I remember from NodeBB forum that you're not supporting your plugins anymore. I just wanted to double-check, if there's any chance you might work on that.

Thanks!
Alex

**Comment by yariplus** [comment]
Should be working now!
